version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers

    environment:
      JVM_OPTS: -Xmx3G
      TERM: dumb

    steps:
      - checkout
      - run:
          name: Checksum
          command: echo gradle/build_components/* >> /tmp/components
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "/tmp/components" }}
            - v1-dependencies--

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gradle/caches
          key: v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "/tmp/components" }}

      - run: gradle build