version: 2

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build

          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/


jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers

    environment:
      JVM_OPTS: -Xmx3G
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "buildSrc" }}
            - v1-dependencies--

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gradle/caches
          key: v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "buildSrc" }}

      - run: ./gradlew build

  release:
    docker:
      - image: circleci/openjdk:8-jdk-browsers

    environment:
      JVM_OPTS: -Xmx3G
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "buildSrc" }}
            - v1-dependencies--

      - run: ./gradlew release