theme: jekyll-theme-midnight

markdown: kramdown
highlighter: rouge
input: GFM

kramdown:
  syntax_highlighter: rouge
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
