name: Sync Secrets
on:
  workflow_dispatch:
    inputs:
      target_repo:
        type: string
        description: Repository to send Secrets to
        required: true
      token:
        type: string
        description: Personal Access Token
        required: true
jobs:
  sync-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: jpoehnelt/secrets-sync-action@v1.4.1
        with:
          SECRETS: |
            ^(MODRINTH|CURSEFORGE)_TOKEN$
            ^PGP_.*$
            ^OSS_.*$
          REPOSITORIES: |
            ${{ github.event.inputs.target_repo }}
          REPOSITORIES_LIST_REGEX: false
          GITHUB_TOKEN: ${{ github.event.inputs.token }}
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          OSS_USERNAME: ${{ secrets.OSS_USERNAME }}
          OSS_PASSWORD: ${{ secrets.OSS_PASSWORD }}
          PGP_KEY: ${{ secrets.PGP_KEY }}
          PGP_PASSWORD: ${{ secrets.PGP_PASSWORD }}
          
          
