name: Sync Secrets
on:
  workflow_dispatch:
    inputs:
      target_repo:
        type: string
        description: Repository to send Secrets to
        required: true
      token:
        type: string
        description: Personal Access Token
        required: true
jobs:
  sync-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: google/secrets-sync-action@v1.4.1
        with:
          SECRETS: |
            ^.*_TOKEN$
            ^PGP_.*$
            ^OSS_.*$
          REPOSITORIES: |
            ${{ github.event.inputs.target_repo }}
          REPOSITORIES_LIST_REGEX: false
          GITHUB_TOKEN: ${{ github.event.inputs.token }}
          
